apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: "service-mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb  
    spec:
      containers:
      - name: mongodb
        image: mongo:4.0.14-xenial
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongo-vol-claim
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-vol-claim
    spec:
      accessModes: ["ReadWriteOnce"]
      volumeName: mongo-volume
      storageClassName: default
      resources:
        requests:
          storage: 100Mi
