---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxconfig
data:
  default.conf: |
    server {
      listen       80;
      server_name  localhost;
      #charset koi8-r;
      access_log  /var/log/nginx/host.access.log  main;

      location / {
          root   /etc/kub-logs;
          autoindex on;
       }

      }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-logs
  labels:
    app: show-logs
spec:
  selector:
    matchLabels:
      name: show-logs
  template:
    metadata:
      labels:
        name: show-logs
    spec:
      containers:
      - name: show-logs
        image: alexkurtser/show-logs:1.1
        ports:
        - containerPort: 80
          name: nginx
        env:
        - name: MONGO_HOST
          value: "service-mongodb"
        - name:  MONGO_PORT
          value: "27017"
        - name:  MONGO_DB
          value: "imubit"
        - name:  MONGO_COLL
          value: "logs"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: nginxconfig
          mountPath: /etc/nginx/conf.d/
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nginxconfig
        configMap:
          name: nginxconfig


