apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-mongo
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd-mongo
  template:
    metadata:
      labels:
        name: fluentd-mongo
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd-mongo
        image: alexkurtser/fluentd:1.3
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varliblogs
          mountPath: /var/log/containers
          readOnly: true
        - name: genlogfolder
          mountPath: /var/log
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varliblogs
        hostPath:
          path: /var/log/containers
      - name: genlogfolder
        hostPath:
          path: /var/log
